version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd app && npm run dev"
    ports:
      - "8080:3000"
    container_name: portfolio-next